# Generated by Django 5.1.1 on 2025-05-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFilms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tokenSesion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
