# Generated by Django 5.1.1 on 2025-06-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFilms', '0002_user_password_user_tokensesion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('film', 'userName')},
        ),
    ]
