# Generated by Django 5.1.1 on 2025-06-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFilms', '0005_alter_score_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
